### ISSUE TITLE
Parametrize config "where" filter.

### ISSUE THREAD

**Issue by wojciech-ostrowski-esky** [devoteamgcloud/dataform-assertions#18]
Hi,

Is it possible to somehow parametrize the filter defined in the **config** clause?
I tried the following:
`"where": "DATE(UTCDate) >= ${dataform.projectConfig.vars.reported_date}"`
where reported_date is a var defined in dataform.json. But it doesn't compile. I get an error like:
`Syntax error: Unexpected "$" at [9:46].`
Is there a way to pass these variables to assertion js files? Or is hard-coding the condition the only option for now?

Best wishes,
Wojtek Ostrowski

**Comment by hrialan** [comment]
Hello @wojciech-ostrowski-esky,

Can you please try with this and tell me if it works ? 

```js
"where": "DATE(UTCDate) >=" + dataform.projectConfig.vars.reported_date
```

Best,
Hugo

**Comment by wojciech-ostrowski-esky** [comment]
@hrialan this works. Thanks a lot!

Best wishes,
Wojtek
