### ISSUE TITLE
NPM error issue

### ISSUE THREAD

**Issue by aliasoblomov** [devoteamgcloud/dataform-assertions#2]
Thank you for sharing your repository. I encountered an error while trying to add a configuration to the package.json file. I guess you may need to update the npm version in your main code to resolve this issue.

Error :
API request error: NPM Execution error: npm notice npm notice New major version of npm available! 8.18.0 -> 10.5.2 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.2> npm notice Run `npm install -g npm@10.5.2` to update! npm notice npm ERR! code E404 npm ERR! 404 Not Found - GET https://codeload.github.com/devoteamgcloud/dataform-assertions/tar.gz/refs/tags/%5BRELEASE_VERSION%5D npm ERR! 404 npm ERR! 404 'dataform-assertions@https://github.com/devoteamgcloud/dataform-assertions/archive/refs/tags/[RELEASE_VERSION].tar.gz' is not in this registry. npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url. npm ERR! Log files were not written due to the config logs-max=0

**Comment by hrialan** [comment]
Hello @aliasoblomov, 

Please replace in the package URL "[RELEASE_VERSION]" by the latest version. Today the latest version is "v1.1.0".

Here is the release link: [Link](https://github.com/devoteamgcloud/dataform-assertions/releases)

It should work after that!
